// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_App_Movijuntos.Data;

#nullable disable

namespace Web_App_Movijuntos.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019231354_novasTabelas")]
    partial class novasTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_App_Movijuntos.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdLocal")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("Id");

                    b.HasIndex("IdLocal");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdAvaliacao")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdComentario");

                    b.HasIndex("Id");

                    b.HasIndex("IdAvaliacao");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Criterio", b =>
                {
                    b.Property<int>("IdCriterio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCriterio"));

                    b.Property<bool>("BanheiroAcess")
                        .HasColumnType("bit");

                    b.Property<bool>("CaminhoLivre")
                        .HasColumnType("bit");

                    b.Property<bool>("Corrimaos")
                        .HasColumnType("bit");

                    b.Property<int>("IdAvaliacao")
                        .HasColumnType("int");

                    b.Property<bool>("PortasCorredor")
                        .HasColumnType("bit");

                    b.Property<bool>("Rampas")
                        .HasColumnType("bit");

                    b.Property<bool>("SinalizacaoSonora")
                        .HasColumnType("bit");

                    b.Property<bool>("SinalizacaoTatil")
                        .HasColumnType("bit");

                    b.Property<bool>("SinalizaçãoVisual")
                        .HasColumnType("bit");

                    b.Property<bool>("VagasEstacion")
                        .HasColumnType("bit");

                    b.HasKey("IdCriterio");

                    b.HasIndex("IdAvaliacao");

                    b.ToTable("Criterios");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Foto", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdAvaliacao")
                        .HasColumnType("int");

                    b.Property<string>("urlFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFoto");

                    b.HasIndex("IdAvaliacao");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Local", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocal"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocal");

                    b.HasIndex("Id");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Avaliacao", b =>
                {
                    b.HasOne("Web_App_Movijuntos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_App_Movijuntos.Models.Local", "Local")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Comentario", b =>
                {
                    b.HasOne("Web_App_Movijuntos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_App_Movijuntos.Models.Avaliacao", "Avaliacao")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdAvaliacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Criterio", b =>
                {
                    b.HasOne("Web_App_Movijuntos.Models.Avaliacao", "Avaliacao")
                        .WithMany("Criterios")
                        .HasForeignKey("IdAvaliacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Foto", b =>
                {
                    b.HasOne("Web_App_Movijuntos.Models.Avaliacao", "Avaliacao")
                        .WithMany("Fotos")
                        .HasForeignKey("IdAvaliacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Local", b =>
                {
                    b.HasOne("Web_App_Movijuntos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Avaliacao", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Criterios");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Web_App_Movijuntos.Models.Local", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
